node {
  name = "emqx@127.0.0.1"
  data_dir = "/opt/emqx/data"
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
}

listeners.ssl.default {
  bind = "0.0.0.0:8883"
  max_connections = 512000
  ssl_options {
    certfile = "/opt/emqx/etc/certs/cert.pem"
    keyfile = "/opt/emqx/etc/certs/key.pem"
    cacertfile = "/opt/emqx/etc/certs/cacert.pem"
  }
}

authentication = []